// stareSDK barrel — re-exports every included component/hook/type plus theme and design tokens.
// Keep this file a flat list of `export *` lines only: no re-aliasing, no re-shaping. OpenStare's
// shared UI library lives here (#31); the app-coupled components take props and the app keeps the
// data wiring.

// Components
export * from './components/AdminModal.js'
export * from './components/AppCard.js'
export * from './components/AssistantButton.js'
export * from './components/Avatar.js'
export * from './components/Badge.js'
export * from './components/Button.js'
export * from './components/ButtonPalette.js'
export * from './components/ClassificationBanner.js'
export * from './components/ClassifyModal.js'
export * from './components/ClockBadges.js'
export * from './components/CollapsiblePanel.js'
export * from './components/ColorPicker.js'
export * from './components/ContextMenu.js'
export * from './components/Checkbox.js'
export * from './components/Popover.js'
export * from './components/DataTable.js'
export * from './components/Disclosure.js'
export * from './components/DraggablePopup.js'
export * from './components/Facets.js'
export * from './components/FieldSelect.js'
export * from './components/FileDropZone.js'
export * from './components/Flyout.js'
export * from './components/HomeButton.js'
export * from './components/InfoTip.js'
export * from './components/ItemClassificationBar.js'
export * from './components/Input.js'
export * from './components/Label.js'
export * from './components/MDText.js'
export * from './components/Modal.js'
export * from './components/MultiSelect.js'
export * from './components/OpacitySlider.js'
export * from './components/PageHeader.js'
export * from './components/Pagination.js'
export * from './components/ProfileChart.js'
export * from './components/PopoverMenuButton.js'
export * from './components/RampPicker.js'
export * from './components/SaveButton.js'
export * from './components/Select.js'
export * from './components/SideNav.js'
export * from './components/Slider.js'
export * from './components/SortableList.js'
export * from './components/Stepper.js'
export * from './components/Tabs.js'
export * from './components/Toast.js'
export * from './components/Toggle.js'
export * from './components/Tooltip.js'
export * from './components/Tree.js'
export * from './components/UnitSelect.js'
export * from './components/TypeaheadPicker.js'
export * from './components/VirtualList.js'
export * from './components/ZoomRangeSlider.js'

// Helpers
export * from './components/CollapsiblePanel.helpers.js'
export * from './components/SortableList.helpers.js'
export * from './components/TypeaheadPicker.helpers.js'
export * from './components/badgeTokens.js'
export * from './components/headerControls.js'
export * from './components/mermaidRender.js'
export * from './components/sideNavStorage.js'
export * from './components/useToast.js'

// Dock (SideNav stacking)
export * from './context/DockContext.js'
export * from './context/useDock.js'

// Theme
export * from './theme/ThemeContext.js'
export * from './theme/useTheme.js'

// Design tokens
export * from './styles/chromeTheme.js'
export * from './units/units.js'
